from abc import ABC, abstractmethod

import torch
from pandas import DataFrame
from pydantic import BaseModel, ConfigDict, Field, model_validator

from kernel_elastic_autoencoder.config import ModelConfig
from kernel_elastic_autoencoder.tokenizer import Tokenizer


class Collated(BaseModel):
    """Return schema for Collator.__call__. Represents a store of tensors ready for direct input to a Model."""

    model_config = ConfigDict(arbitrary_types_allowed=True)
    input_ids: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, S) containing indices of input tokens, generated by a Tokenizer.",
    )
    conditions: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, C) containing condition values for each sequence.",
    )
    token_mask: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, S) containing a boolean padding mask for each sequence.",
    )
    condition_mask: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, C) containing a boolean condition mask for each sequence",
    )

    @model_validator(mode="after")
    def _check_shapes(self) -> "Collated":
        if (self.input_ids.shape != self.token_mask.shape) or (
            self.conditions.shape != self.condition_mask.shape
        ):
            raise ValueError("Mask shapes don't match source")
        if (self.input_ids.dim() != 2) or (self.conditions.dim() != 2):
            raise ValueError("Tensors should have a batch dimension")
        if (self.token_mask.dtype != torch.bool) or (
            self.condition_mask.dtype != torch.bool
        ):
            raise ValueError("Mask tensors should have bool dtype")
        return self


class Collator[T](ABC):
    """Base class for collators.

    Provides a specification for preparing various data types for model input.
    """

    def __init__(self, model_config: ModelConfig, tokenizer: Tokenizer):
        """Instantiates a Collator object.

        Args:
            model_config: Model configuration object.
            tokenizer: Object implementing the Tokenizer protocol.
        """
        self.model_config = model_config
        """Model configuration object."""
        self.tokenizer = tokenizer
        """Object implementing the Tokenizer protocol."""

    def __call__(
        self,
        dataset: T,
        seq_feature: str,
        cond_features: list[str],
        padding: bool,
        add_special_tokens: bool,
        device: torch.device | None,
        **kwargs,
    ) -> Collated:
        return self.collate_data(
            dataset,
            seq_feature,
            cond_features,
            padding,
            add_special_tokens,
            device,
            **kwargs,
        )

    @abstractmethod
    def collate_data(
        self,
        dataset: T,
        seq_feature: str,
        cond_features: list[str],
        padding: bool,
        add_special_tokens: bool,
        device: torch.device | None,
        **kwargs,
    ) -> Collated:
        """Interface method for implementing data collation.

        Args:
            dataset: Dataset object of target data type.
            seq_feature: Name of sequence feature or column.
            cond_features: List of names of condition features or columns.
            padding: Whether or not to uniformly pad outputs to the maximum length specified in the model configuration.
            add_special_tokens: Whether or not to add special tokens according to a template. Special tokens will be
                added by default during training, but will be omitted during inference, where the specified bos_token_id
                will be appended before each pass through the decoder.
            device: Torch device to which the produced tensors are moved.
            **kwargs: Keyword arguments.

        Returns:
            Collated: Return schema representing a store of tensors ready for direct input to a Model.
        """
        ...


class DataframeCollator(Collator):
    """Collator designed for pandas.DataFrame inputs."""

    def collate_data(
        self,
        dataset: DataFrame,
        seq_feature: str,
        cond_features: list[str],
        padding: bool,
        add_special_tokens: bool,
        device: torch.device | None,
        **kwargs,
    ) -> Collated:
        """Implementation of data collation for pandas.DataFrame inputs.

        Args:
            dataset: Dataset object of pandas.DataFrame type.
            seq_feature: Name of sequence column.
            cond_features: List of names of condition columns.
            padding: Whether or not to uniformly pad outputs to the maximum length specified in the model configuration.
            add_special_tokens: Whether or not to add special tokens according to a template. Special tokens will be
                added by default during training, but will be omitted during inference, where the specified bos_token_id
                will be appended before each pass through the decoder.
            device: Torch device to which the produced tensors are moved.
            **kwargs: Keyword arguments passed to Tokenizer.encode.

        Returns:
            Collated: Return schema representing a store of tensors ready for direct input to a Model.
        """
        df = dataset.copy()
        input_ids = self.tokenizer.encode(
            seq=df[seq_feature],
            padding=padding,
            max_length=self.model_config.input.max_len,
            add_special_tokens=add_special_tokens,
            **kwargs,
        )
        conditions = torch.from_numpy(df[cond_features].to_numpy()).to(
            device=device, dtype=torch.float
        )
        token_mask = (input_ids != self.model_config.common.padding_idx).to(torch.bool)
        condition_mask = (conditions != self.model_config.common.padding_value).to(
            torch.bool
        )
        return Collated(
            input_ids=input_ids,
            conditions=conditions,
            token_mask=token_mask,
            condition_mask=condition_mask,
        )
