import torch
from pydantic import BaseModel, ConfigDict, Field, model_validator


class Collated(BaseModel):
    """Store of tensors ready for direct input to a Model."""

    model_config = ConfigDict(arbitrary_types_allowed=True)
    input_ids: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, S) containing indices of input tokens, generated by a Tokenizer.",
    )
    conditions: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, C) containing condition values for each sequence.",
    )
    token_mask: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, S) containing a boolean padding mask for each sequence.",
    )
    condition_mask: torch.Tensor = Field(
        ...,
        description="Tensor of dimension (B, C) containing a boolean condition mask for each sequence",
    )

    @model_validator(mode="after")
    def _check_shapes(self) -> "Collated":
        if (self.input_ids.shape != self.token_mask.shape) or (
            self.conditions.shape != self.condition_mask.shape
        ):
            raise ValueError("Mask shapes don't match source")
        if (self.input_ids.dim() != 2) or (self.conditions.dim() != 2):
            raise ValueError("Tensors should have a batch dimension")
        if (self.token_mask.dtype != torch.bool) or (
            self.condition_mask.dtype != torch.bool
        ):
            raise ValueError("Mask tensors should have bool dtype")
        return self
